language: node_js

git:
  depth: 10000
node_js:
  - "8"
install:
  - npm run setup
before_script:
  # - npm run lint || true
script:
  - npm run production
  - npm run test
  - cd dist; echo "./fetchTravisBuild.sh stellarterm-build-output/stellarterm/stellarterm/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/dist/index.html $(openssl dgst -sha256 index.html | sed 's/^.* //')"
  - npm run hash

addons:
  artifacts:
    secret:
      secure: K+WCWifkX+7AMZ73tspCU2/pS50tPYnH6DtZGQInoxSZHR44WO29aqF0l3kpmLv86We4FzD/hqt4zibOavvtV7+Fk9qRuwnFMfDcFaaneYbuQnKlvW5IRO0+PQkNKYkgxSK6RJISaclZ8D/ua/jjtFkuP7Cvnnfgs0HUEI/3mIn+EZfyzSvzLZBY0nM8hHcBwkdJheexIDxe6vv463g/eEOJDPQYjlgYyVCgchIXfW5UTeNoRkIJNe6UmjyNBWNFQMt/J0+dk/ryphj1o+tNpvHO5Jgh2UEPHTuTXvCFVk//+89QWyk8taAIql87+fEGlZ2wecUmVgjHpE0natpEmar5lExzAQN7YAgm8QMtxEKmOqWKebp9Ahp8Ws1QtuDDQJUPejkHBSYtkeA7OqDpMOFD5u4s6eentu/AJ9MOIsl5wW+ib7pHu+Q9zD/D9yxFH/G5VuJK0pqWmCvKShn+9zP8XE/dmhh+P80GBBGW4Q40r61g5D3/ShtP8Q/rwW07JG8v2AZXFMj6yezuKIkh7Vo/Q5gciuF7UKOAo5SH73HBOJwpFOPWP7A21Hu+0QggloCR3wD4QYKfvVwqK0EMVHrKzBjam0q4BGqisrTE1A4fo+LutTC1Juzd/D4tXdqM3wMjTss9SLIdCa7A+hQu9gckUMAkXcJVhV870QY9LEA=
    bucket: stellarterm-build-output
    key:
      secure: C4xjYYkzvHRuy+0KiDL21/J4T39rClfZFFLYPI+i21TeL1pclkNSFZSyqLFk8ToMfp3tgVv8D9hbUu/Glxg0kyUSkrUAGYRahGMlZC8+cfP+WFiFUR5gAfCkQAr/sx+y8kRgMlMwzD3SwRqoDH42riGFvCv0f9MScPZVxTeQIkLri7yPoXcv1ZiEPt7nCL3B/mJmm7iPebuFzcYMNiITIggoOnOHq+V5lq8BMWB1Y1pK9d/RoVDFJVKgExJpLdUZyg5agq8h4OByXCFN6zWk4f0ombch0wt1liGDrrKK59J8rbS8L7aXrp5jJyy4/sHIhf7bziSmmA8k5nFJmyNtaVqWMv8osMwwYtVnAavOushKbabzxImAc9kaKbNb3R3sUiwqecKDoC2DDyYihyEZeKgrb5+37xTpYgcSLqZWm/aZHkgeM7pjmP58sAQ9VgCWzoGSnn12A9rBCD+sLRQ0Wqtfh5HmheiIELx4TN4a6TZpt4wDV5debza1nzV46DO6zuDYbQ3vO62LKS8xa5elpy+662QmuVyfuPe56eQnYI7r/hUTINspnfbbur4qRrzO+ZXgsc15vAf5P+Sop95C43ZcQo9lk2V8T+nsr4a7GWlM6zY+TZ8y9NIKJ4P4poXryCEdAcc6WQJdnzStoFyPGcTCIq8urhX9KFciyAroOLA=
    paths:
      - /home/travis/build/stellarterm/stellarterm/dist/index.html
